# file: group_vars
################################################################################
#
#                  ////IMPORTANT////
#
#      Prefixed to all resources for cleanup & identifcation.
################################################################################

# Ensure that the name does not include special characters such as underscores, etc.
workshop_prefix:                  "monitoring"
execution:                        "local" # when not running from Tower, define this variable
graphical:                        "true" # when true, install a graphical desktop on the tower nodes

################################################################################
# ANSIBLE ROLE KEY         |      VALUE
################################################################################
# aws                      |      deployment working dir 
deploy_working_dir:               "{{ lookup('env','PWD') }}/.redhatgov"
# aws                      |      AWS API KEYS
aws_access_key:                   ""
aws_secret_key:                   ""
# aws                      |      AWS Route 53
domain_name:                      ""
zone_id:                          ""
# aws                      |      AWS Node Counts
rhel_count:                       "2"            # RHEL node(s)
win_count:                        "2"            # Windows node(s)
region:                           "us-east-2"    # AWS Region, configures ec2.ini too
ebs_root_block_size:              50
# aws.infra                |      AWS AMI IDs
#-------------------------------------------------------------------------------
# us-east-1
# rhel_ami_id:                "ami-0456c465f72bd0c95" # RHEL-7.5_HVM-20180813-x86_64-0-Access2-GP2
# rhel_ami_id:                "ami-0240b09539b9692a0" # RHEL-7.6_HVM_GA-20190128-x86_64-0-Access2-GP2
# rhel_ami_id:                "ami-0729967d6d95d8317" # RHEL-8.0.0_HVM-20190426-x86_64-1-Access2-GP2
# win_ami_id:                 "ami-0bf148826ef491d16" # Windows_Server-2016-English-Full-Base-2019.02.13
# us-east-2
#rhel_ami_id:                "ami-04268981d7c33264d" # RHEL-7.5_HVM-20180813-x86_64-0-Access2-GP2
rhel_ami_id:                "ami-0ee3b6d31319e5fde" # RHEL-7.6_HVM_GA-20190128-x86_64-0-Access2-GP2
# rhel_ami_id:                "ami-0bc2bdfd487d3ae8d" # RHEL-8.0.0_HVM-20190426-x86_64-1-Access2-GP2
# win_ami_id:                 "ami-08b4a0f6e106c1dba" # Windows_Server-2016-English-Full-Base-2019.02.13
#-------------------------------------------------------------------------------
# instance_types
win_instance_type:                "t3.large"
tower_instance_type:              "t3.large"
rhel_instance_type:               "t3.small"
#-------------------------------------------------------------------------------
# subscription_manager     |      Red Hat Subscription via Cloud Access
cloud_access:                     true
# subscription_manager     |      Red Hat Subscription via username & password
username:                         ""
password:                         ""
pool_id:                          ""
# subscription_manager     |      Red Hat Subscription via activation keys
rhsm_activationkey:               ""
rhsm_org_id:                      ""
#-------------------------------------------------------------------------------
# LetsEncrypt              |      email
letsencrypt_email:                "someone@redhat.com"
letsencrypt:                      false
#-------------------------------------------------------------------------------
# wetty                    |      password
workshop_password:                "" # Note that Windows 2016 requires 3 character classes and 10 characters
#-------------------------------------------------------------------------------

################################################################################
# ANSIBLE config           |      VALUE
################################################################################
# Dynamic Inventory 
inventory_working_dir:            "{{ lookup('env','PWD') }}/inventory"
# Ansible SSH Key Location |      SSH Key Vars
winrm_path:                       "{{ deploy_working_dir }}/{{ workshop_prefix }}-winrm"
ssh_key_path:                     "{{ deploy_working_dir }}/{{ workshop_prefix }}-key"
vpc_id_path:                      "{{ deploy_working_dir }}/{{ workshop_prefix }}-vpc_id"
vpc_route_path:                   "{{ deploy_working_dir }}/{{ workshop_prefix }}-vpc_route"
vpc_subnet_path:                  "{{ deploy_working_dir }}/{{ workshop_prefix }}-vpc_subnet"
vpc_rhel_ids_path:                "{{ deploy_working_dir }}/{{ workshop_prefix }}-vpc_rhel_ids"
ansible_ssh_private_key_file:     "{{ ssh_key_path }}"
system_user:                      "ec2-user"    # AWS
local_user:                       "{{ ansible_env.USERNAME }}" # on RHEL/Fedora
# local_user:                       "{{ ansible_env.USER }}" # on Mac OS X
