# file: roles/openshift.prereq/tasks/rhsm.yml
---

- name: Disable RHUI plugins
  lineinfile: dest={{ item }} regexp='^enabled' line='enabled=0' state=present
  with_items: "{{ rhel_rhui_plugins }}"

- name: Disable RHUI repositories
  replace:
    dest: "{{ item }}"
    regexp: 'enabled=1'
    replace: 'enabled=0'
  with_items: "{{ rhel_rhui_repos }}"

- name: Enable RHSM plugins
  lineinfile: dest={{ item }} regexp='^enabled' line='enabled=1' state=present
  with_items: "{{ rhel_rhsm_plugins }}"

- name: Register with RHSM
  redhat_subscription: state=present activationkey='{{ rhel_rhsm_activationkey }}' org_id='{{ rhel_rhsm_org_id }}'

- name: Disable all RHSM repositories
  shell: subscription-manager repos --disable="*"

- name: Disable all yum repositories
  shell: /usr/bin/yum-config-manager --disable \*

- name: Enable only the repositories required
  shell: subscription-manager repos --enable {{ item }}
  with_items: "{{ rhel_rhsm_repos }}"

- name: Enable only the repositories required
  shell: subscription-manager repos --enable {{ rhel_rhsm_repo_ocp_v3_4 }}
  when: openshift_release == "3.4"

- name: Enable only the repositories required
  shell: subscription-manager repos --enable {{ rhel_rhsm_repo_ocp_v3_5 }}
  when: openshift_release == "3.5"

# - name: Import Red Hat beta test products key
#   rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta
#   ignore_errors: True
