# file: roles/wetty/tasks/main.yml
---

- name: Install Make & GCC
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - make
    - gcc-c++

- name: Install Wetty Globaly
  become: yes
  command: npm install wetty -g chdir=/home/ec2-user

<<<<<<< HEAD

#-------------------------------------------------------
# Let's Encrypt. 
#-------------------------------------------------------
- name: Copy cert.pem to Wetty dir
  become: yes
  command: cp cert.pem /home/{{ system_user }}/.ssh/ chdir="/etc/letsencrypt/live/{{ workshop_prefix | lower }}.{{ hostvars[inventory_hostname]['ec2_tag_Index'] }}.{{ domain_name }}/"  
  when: letsencrypt
=======
# Depends on Let's Encrypt. 
- name: Copy Cert.pem to Wetty dir
  become: yes
  command: cp cert.pem /home/{{ system_user }}/.ssh/ chdir="/etc/letsencrypt/live/{{ workshop_prefix | lower }}.{{ hostvars[inventory_hostname]['ec2_tag_Index'] }}.{{ domain_name }}/"  
  when: aws
>>>>>>> 85f34e3fb70678360017bbf1e10f4751eb7bc38d

- name: Copy privkey.pem to Wetty dir
  become: yes
  command: cp privkey.pem /home/{{ system_user }}/.ssh/ chdir="/etc/letsencrypt/live/{{ workshop_prefix | lower }}.{{ hostvars[inventory_hostname]['ec2_tag_Index'] }}.{{ domain_name }}/" 
<<<<<<< HEAD
  when: letsencrypt

#-------------------------------------------------------
# Self-Signed Certs 
#-------------------------------------------------------
- name: Generate Self Signed Certs
=======
  when: aws

- name: Generate Self Signed Certs fro Vagrant
>>>>>>> 85f34e3fb70678360017bbf1e10f4751eb7bc38d
  command: >
    openssl req -new
      -x509
      -nodes
      -days {{ item.days | default(3650) }}
      -subj "/C={{ item.country | default('') }}/ST={{ item.state | default('') }}/L={{ item.city | default('') }}/O={{ item.organization | default('') }}/OU={{ item.unit | default('') }}/CN={{ item.name }}/emailAddress={{ item.email | default('') }}"
      -newkey rsa:2048
      -keyout /home/{{ system_user }}/.ssh/privkey.pem
      -out /home/{{ system_user }}/.ssh/cert.pem
  with_items: "{{ openssl_self_signed }}"
<<<<<<< HEAD
  when: not letsencrypt
=======
  when: not aws  
>>>>>>> 85f34e3fb70678360017bbf1e10f4751eb7bc38d

- name: Set permissions on SSL certs
  become: yes
  file: 
    path:    "/home/{{ system_user }}/.ssh/{{ item }}"
    group:   "{{ system_user }}"  
    owner:   "{{ system_user }}"
    mode:    0400
  with_items: 
    - cert.pem
    - privkey.pem

# TODO: SELinux & Systemd
- name: Sorry Dan.
  become: yes
  command: setenforce 0
<<<<<<< HEAD

=======
  when: aws
>>>>>>> 85f34e3fb70678360017bbf1e10f4751eb7bc38d

# SYSTEMD
- name: Template Systemd Service File 
  become: yes
  template:
    src:   "wetty.service.j2"
    dest:  "/etc/systemd/system/wetty.service"
    group: root 
    owner: root
    mode:  0644
  notify: wetty

# password_hash requires the passlib python module to generate password hashes
# pip install passlib
- name: Set ec2-user password
  become: yes
  user:   
    name:      "ec2-user"
    password:  "{{ workshop_password |password_hash('sha512') }}"   
    state:     present
    append:    yes


- name: Update SSH Config
  become: yes
  copy:
    src: sshd_config
    dest: "/etc/ssh/sshd_config"
    group: root
    owner: root
    mode: 0644 
  notify: 
    - sshd  

###########################################################
#   Build from Source
###########################################################
# - name: Clone Wetty
#   git:
#     clone: yes
#     force: yes
#     dest:  "/home/{{ system_user }}/.wetty"
#     repo:  "https://github.com/krishnasrinivas/wetty"
#
# - name: Set permissions on repo
#   become: yes
#   file: 
#     recurse: yes
#     path:    "/home/{{ system_user }}/.wetty"
#     group:   "{{ system_user }}"  
#     owner:   "{{ system_user }}"
#     mode:    0700
#
# - name: Install wetty
#   command: npm install chdir="/home/{{ system_user }}/.wetty"