---

- name: Create private zone for openshift
  route53_zone:
     zone: "{{ intranet }}"
     state: "present"
     vpc_id: "{{ vpc_id }}"
     vpc_region: "{{ aws_region }}"
     comment: "Internal zone for Openshift"
     aws_access_key: "{{ aws_access_key }}"
     aws_secret_key: "{{ aws_secret_key }}"
  register: intranet_zone

# - debug: msg="{{ aws_zone }}"

- name: Set private zone id
  set_fact:
    intranet_zone_id: "{{ intranet_zone['result']['zone_id'] }}"

- name: Add bastion to private zone
  route53:
    hosted_zone_id: "{{ intranet_zone_id }}"
    zone: "{{ intranet }}"
    record: "{{ ec2_bastion_tag }}.{{ intranet }}"
    type: A
    ttl: 300
    value: "{{ bastion_private_ip }}"
    wait: yes
    vpc_id: "{{ vpc_id }}"
    private_zone: true
    command: "create"
    overwrite: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

- name: Add master to private zone
  route53:
    hosted_zone_id: "{{ intranet_zone_id }}"
    zone: "{{ intranet }}"
    record: "{{ ec2_master_tag }}.{{ intranet }}"
    type: A
    ttl: 300
    value: "{{ master_private_ip }}"
    wait: yes
    vpc_id: "{{ vpc_id }}"
    private_zone: true
    command: "create"
    overwrite: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

- name: Add node to private zone
  route53:
    hosted_zone_id: "{{ intranet_zone_id }}"
    zone: "{{ intranet }}"
    record: "{{ ec2_node_tag }}{{ item.index }}.{{ intranet }}"
    type: A
    ttl: 300
    value: "{{ item.private_ip }}"
    wait: yes
    vpc_id: "{{ vpc_id }}"
    private_zone: true
    command: "create"
    overwrite: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  with_items: "{{  nodes_ip  }}"

- name: Add gluster to private zone
  route53:
    zone: "{{ intranet }}"
    record: "{{ ec2_gluster_tag }}{{ item.index }}.{{ intranet }}"
    type: A
    ttl: 300
    value: "{{ item.private_ip }}"
    wait: yes
    vpc_id: "{{ vpc_id }}"
    private_zone: true
    command: "create"
    overwrite: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  with_items: "{{ nodes_ip }}"
  when: install_gluster

- name: Add master to public zone
  route53:
    zone: "{{ domain }}"
    record: "{{ domain }}"
    type: A
    ttl: 300
    value: "{{ master_public_ip }}"
    wait: yes
    command: "create"
    overwrite: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

- name: Add wildcard to public zone
  route53:
    zone: "{{ domain }}"
    record: "*.{{ wildcard }}"
    type: A
    ttl: 300
    value: "{{ master_public_ip }}"
    wait: yes
    command: "create"
    overwrite: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
