# file: group_vars/vault

#####################################################
# Default vault configuration
#####################################################
vault_default_domain:    "${INSERT_VALUE_HERE}"
vault_cluster_name:      "${INSERT_VALUE_HERE}"
vault_cluster_id:        "bdsa"
vault_openshift_release: "3.11"
vault_users_count:       20
vault_redhat_uid:        "${INSERT_VALUE_HERE}"
vault_redhat_pwd:        "${INSERT_VALUE_HERE}"

#####################################################
# AWS access keys
#####################################################
vault_aws_access_key_id:     "${INSERT_VALUE_HERE}"
vault_aws_secret_access_key: "${INSERT_VALUE_HERE}"

#####################################################
# AWS R53 Zone ID
#####################################################
vault_aws_route53_zone_id: "${INSERT_VALUE_HERE}"

#####################################################
# Red Hat Subscription Information 
#####################################################
# To subscribe with activation keys:
vault_rhel_rhsm_activationkey: "${INSERT_VALUE_HERE}"
vault_rhel_rhsm_org_id:        "${INSERT_VALUE_HERE}"
# To subscribe with username and password + pool id:
vault_rhsm_pool_id:            "${INSERT_VALUE_HERE}"

#####################################################
# Cluster administration
#####################################################
vault_openshift_cluster_admin_username: "${INSERT_VALUE_HERE}"
vault_openshift_cluster_admin_password: "${INSERT_VALUE_HERE}"

#####################################################
# Node information
#####################################################
vault_number_nodes: "2"
vault_master_size:  "m4.2xlarge"
vault_node_size:    "m4.xlarge"
vault_ami:          "ami-b63769a1"  # RHEL7.3
#vault_ami:          "ami-000db10762d0c4c05"  # RHEL7.6 - untested
#vault_ami:          "ami-0916c408cb02e310b"  # RHEL7.7 - DO NOT USE, breaks deploy
