---

- name: List all hosted zones
  route53_facts:
    query: hosted_zone
  register: hosted_zones

- name: Delete master and bastion routes
  include: delete-route.yml zone={{ intranet }} record=""{{ item }}".{{ intranet }}" private_zone="true"
  with_items:
    - "{{ ec2_bastion_tag }}"
    - "{{ ec2_master_tag }}"

- name: Delete node routes
  include: delete-route.yml zone={{ intranet }} record="{{ ec2_node_tag }}{{ item }}.{{ intranet }}" private_zone="true"
  with_sequence: start=1 end={{ ec2_instance_count|int }}
  ignore_errors: true

- name: Delete gluster routes
  include: delete-route.yml zone={{ intranet }} record="{{ ec2_gluster_tag }}{{ item }}.{{ intranet }}" private_zone="true"
  with_sequence: start=1 end={{ ec2_instance_count|int }}
  ignore_errors: true

- name: Delete private DNS zone for openshift
  route53_zone:
     zone: "{{ intranet }}"
     state: "absent"
     vpc_region: "{{ aws_region }}"
     comment: "Internal zone for Openshift"
  ignore_errors: yes

- name: Delete Public Route
  include: delete-route.yml zone={{ domain }} record={{ domain }} private_zone="false"

- name: Delete Public Wildcard Route
  include: delete-route.yml zone={{ domain }} record="*.{{ wildcard }}" private_zone="false"
