---

- name: List all hosted zones
  route53_facts:
    query: hosted_zone
  register: hosted_zones

- name: Delete master and bastion routes
  include: delete-route.yml zone={{ intranet }} record="{{ item }}.{{ intranet }}" private_zone="true"
  with_items:
    - "{{ ec2_bastion_tag }}"
    - "{{ ec2_master_tag }}"

- name: Delete node routes
  include: delete-route.yml zone={{ intranet }} record="{{ ec2_node_tag }}{{ item }}.{{ intranet }}" private_zone="true"
  with_sequence: start=1 end={{ ec2_instance_count|int }}
  ignore_errors: true

- name: Delete gluster routes
  include: delete-route.yml zone={{ intranet }} record="{{ ec2_gluster_tag }}{{ item }}.{{ intranet }}" private_zone="true"
  with_sequence: start=1 end={{ ec2_instance_count|int }}
  ignore_errors: true

- name: Get private DNS hosted zone ID
  shell: aws route53 list-hosted-zones --query 'HostedZones[*]' --output text | grep '\/hostedzone\/.*{{ intranet }}' | sed -e 's/.*\///' -e 's/[^a-zA-Z0-9].*//'
  register: hosted_zone_id

- debug: var=hosted_zone_id.stdout_lines[0]

- name: Delete private DNS hosted zone ID
  shell: aws route53 delete-hosted-zone --id '{{ hosted_zone_id.stdout_lines[0] }}'
  when: hosted_zone_id.stdout_lines[0] is defined

- name: Delete public route
  include: delete-route.yml zone={{ domain }} record={{ domain }} private_zone="false"

- name: Delete public wildcard Route
  include: delete-route.yml zone={{ domain }} record="*.{{ wildcard }}" private_zone="false"
