---

domain: "{{ vault_domain }}"
prefix: "{{ vault_prefix }}"
wildcard: "{{ prefix }}.{{ domain }}"
namespace: "{{ vault_namespace }}"
suffix: "{{ vault_suffix }}"
intranet: "{{ vault_intranet }}"
app_id: "{{ vault_app_id }}"
role: "{{ vault_role }}"
cluster: "{{ vault_cluster }}"
deploy_env: "{{ vault_deploy_env }}"
release: "{{ vault_release }}"
workspace: "{{ lookup('env','PWD') }}/.{{ domain }}"
http_port: 80
http_proxy_port: 8080
https_port: 443
https_proxy_port: 8443
dns_port: 8053
vxlan_port: 4789
es_port: 9300
es_proxy_port: 9200
etcd_port: 2380
etcd_proxy_port: 2379
kubelet_port: 10250
ssh_port: 22

#---------------------------------------------------
# Remote User
#---------------------------------------------------
remote_user_name: "{{ vault_remote_user_name }}"
remote_user_key: "{{ vault_remote_user_key }}"
remote_user_key_file: "{{ workspace }}/{{ remote_user_key }}"
remote_user_home: "/home/{{ remote_user_name }}"
remote_user_ssh_path: "{{ remote_user_home }}/.ssh"
remote_user_ssh_conf: "{{ remote_user_ssh_path }}/config"

#---------------------------------------------------
# Subscription Manager
#---------------------------------------------------
# Uncomment to use customer portal login credentials:
# rhsm_user_name: "{{ vault_rhsm_user_name }}"
# rhsm_user_pass: "{{ vault_rhsm_user_pass }}"
# rhsm_pool_id: "{{ vault_rhsm_pool_id }}"

# See https://access.redhat.com/articles/1378093
rhsm_key_id: "{{ vault_rhsm_key_id }}"
rhsm_org_id: "{{ vault_rhsm_org_id }}"

#---------------------------------------------------
# Ansible Engine
#---------------------------------------------------
ansible_user: "{{ remote_user_name }}"
ansible_ssh_private_key_file: "{{ remote_user_key_file }}"

#---------------------------------------------------
# Amazon web Services
#---------------------------------------------------
aws_access_key: "{{ vault_aws_access_key }}"
aws_secret_key: "{{ vault_aws_secret_key }}"
aws_region: "{{ vault_aws_region }}"
aws_az: "{{ aws_region }}a"

# Network
route53_hosted_zone_id: "{{ vault_aws_zoneid }}"

vpc_cidr_block: 10.0.0.0/16
public_subnet_1_cidr: 10.0.0.0/24
public_route_cidr_block: 0.0.0.0/0

# VPC with public/private subnets
# private_subnet_1_cidr: "10.0.1.0/24"

# VPC with public/private subnets and multi availability zones
# public_subnet_2_cidr: "10.0.10.0/24"
# private_subnet_2_cidr: "10.0.11.0/24"

# Tags
ec2_tag: "{{ prefix }}-{{ namespace }}-{{ suffix }}"
ec2_master_tag: master
ec2_node_tag: node
ec2_gluster_tag: gluster
ec2_bastion_tag: bastion

vpc_tag: "{{ namespace }}-vpc"
vpc_subnet_tag: "{{ namespace }}-subnet"
vpc_route_tag: "{{ namespace }}-route"

# Groups
ec2_security_group: "{{ namespace }}-default-sg"
ec2_security_group_ingress: "{{ namespace }}-ingress-sg"
ec2_security_group_egress: "{{ namespace }}-egress-sg"
ec2_security_group_ssh: "{{ namespace }}-ssh-sg"

ec2_master_group: "{{ namespace }}-{{ ec2_master_tag }}"
ec2_bastion_group: "{{ namespace }}-{{ ec2_bastion_tag }}"
ec2_node_group: "{{ namespace }}-{{ ec2_node_tag }}"

# Instance
redhat_owner_id: 309956199498
# ec2_master_image: # Look up image manually
# ec2_node_image: # Look up image manually
# ec2_bastion_image: # Look up image manually
ec2_master_instance_type: m4.xlarge
ec2_node_instance_type: t2.large
ec2_bastion_instance_type: t2.small
ec2_gluster_instance_type: m4.xlarge
ec2_instance_count: 3

# System
os_master_root_vol_size: 50
os_node_root_vol_size: 30
os_bastion_root_vol_size: 15

# Docker
os_docker_block_device: /dev/xvdb
os_docker_volume_group: docker-vg
os_docker_vol_size: 50

# Gluster (size is per node, e.g. total storage is os_gluster_vol_size * 3)
os_gluster_block_device: /dev/xvdc
os_gluster_vol_size: 100

#---------------------------------------------------
# Ansible Tower
#---------------------------------------------------
# awx_user_name: "{{ vault_awx_user_name }}"
# awx_user_pass: "{{ vault_awx_user_pass }}"

#---------------------------------------------------
# OpenShift Container Platform
#---------------------------------------------------
# Must be either origin or openshift-enterprise
platform: openshift-enterprise
version: 3.7
htpasswd_path: /etc/origin/master/htpasswd
install_metrics: true
install_prometheus: false
install_logging: true
install_gluster: false

admin_username: "{{ vault_admin_username }}"
admin_password: "{{ vault_admin_password }}"

student_name_prefix: "{{ vault_student_name_prefix }}"
student_pass_prefix: "{{ vault_student_pass_prefix }}"
student_count: "{{ vault_student_count }}"
