---
# tasks file for roles/aws.create
#===============================================================================
#  Provisioning
#===============================================================================

- name: RHEL AMI
  debug:
    msg: "Using AWS {{ region }} {{ rhel_ver }} AMI: {{ regions[region][rhel_ver].ami }}"

- name: Windows AMI
  debug:
    msg: "Using AWS {{ region }} {{ win_ver }} AMI: {{ regions[region][win_ver].ami }}"

#---------------------------------------------------
#  Ansible Hosts Creation
#---------------------------------------------------
- name: Template Ansible Hosts File
  template:
    dest: "{{ inventory_working_dir }}/hosts"
    src: "hosts.j2"
  when: execution is defined

#---------------------------------------------------
#  Deployment directory creation
#---------------------------------------------------
- name: Make temporary location to run deployment
  file:
    path: "{{ deploy_working_dir }}"
    state: directory

#---------------------------------------------------
#  WinRM templating
#---------------------------------------------------
- name: Template Windows WinRM configuration
  template:
    dest: "{{ winrm_path }}"
    src: "winrm.txt.j2"

#---------------------------------------------------
#  EC2 INI Creation
#---------------------------------------------------
- name: Template EC2 INI File
  template: dest="{{ inventory_working_dir }}/ec2.ini"  src=ec2.ini.j2
  when: execution is defined

#---------------------------------------------------
#  SSH Key
#---------------------------------------------------
- name: Create EC2 keypair
  ec2_key:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    region: "{{ region }}"
    state: present
  register: ec2_key

- debug:
    var: ec2_key

- name: Create ssh keypair
  copy:
    content: "{{ ec2_key.key.private_key }}\n"
    dest: "{{ ssh_key_path }}"
    mode: 0400
  when: ec2_key.changed

#---------------------------------------------------
#  Create AWS objects
#---------------------------------------------------
- name: Create VPC
  ec2_vpc_net:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-vpc"
    region: "{{ region }}"
    cidr_block: "10.0.0.0/16"
    dns_hostnames: yes
    dns_support: yes
    tags:
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
    state: present
  register: ec2_vpc

- debug:
    var: ec2_vpc

- name: Create VPC internet gateway
  ec2_vpc_igw:
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    state: present
    tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-igw"
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
  register: ec2_igw

- debug:
    var: ec2_igw

- name: Create RHEL security group
  ec2_group:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    description: "SG for RHEL hosts"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    rules:
    - proto: "tcp"
      ports: 22
      cidr_ip: 0.0.0.0/0
      rule_desc: "allow all on port 22 (SSH)"
    - proto: "tcp"
      ports: 80
      cidr_ip: 0.0.0.0/0
      rule_desc: "allow all on port 80 (http)"
    - proto: "tcp"
      ports: 443
      cidr_ip: 0.0.0.0/0
      rule_desc: "allow all on port 443 (https)"
    - proto: "tcp"
      ports: 3389
      cidr_ip: 0.0.0.0/0
      rule_desc: "allow all on port 3389 (rdp)"
    - proto: "tcp"
      ports: 8080
      cidr_ip: 0.0.0.0/0
      rule_desc: "allow all on port 8080 (jboss)"
    - proto: "tcp"
      ports: 8888
      cidr_ip: 0.0.0.0/0
      rule_desc: "allow all on port 8888 (wetty)"
    - proto: "tcp"
      ports: 9090
      cidr_ip: 0.0.0.0/0
      rule_desc: "allow all on port 9090 (cockpit)"
    tags:
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
      rhel: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
    state: present

- name: Create Windows security group
  ec2_group:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-win-sg"
    description: "SG for Windows hosts"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    rules:
    - proto: "tcp"
      ports: 3389
      cidr_ip: 0.0.0.0/0
      rule_desc: "allow all on TCP port 3389 (Remote Desktop)"
    - proto: "udp"
      ports: 3389
      cidr_ip: 0.0.0.0/0
      rule_desc: "allow all on UDP port 3389 (Remote Desktop)"
    - proto: "tcp"
      ports: 5986
      cidr_ip: 0.0.0.0/0
      rule_desc: "allow all on port 5986 (WinRM HTTPS)"
    tags:
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
      win: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
    state: present

- name: Create public subnet
  ec2_vpc_subnet:
    cidr: "10.0.2.0/24"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-subnet"
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
    wait: yes
  register: ec2_subnet

- name: Create private subnet
  ec2_vpc_subnet:
    cidr: "10.0.3.0/24"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-private-subnet"
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
    wait: yes
  register: ec2_private_subnet

- debug:
    var: ec2_subnet

- name: Create VPC route table
  ec2_vpc_route_table:
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    subnets:
      - "{{ ec2_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ ec2_igw.gateway_id }}"
    lookup: tag
    tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-route"
      username: "{{ local_user }}"
      workshop: "{{ workshop }}"
      workshop_prefix: "{{ workshop_prefix }}"
    state: present
  register: ec2_route

- debug:
    var: ec2_route

- name: Create RHEL instances
  ec2:
    assign_public_ip: yes
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    instance_type: "{{ rhel_instance_type }}"
    image: "{{ regions[region][rhel_ver].ami }}"
    vpc_subnet_id: "{{ ec2_subnet.subnet.id }}"
    wait: true
    instance_tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel"
      username: "{{ local_user }}"
      workshop_prefix: "{{ workshop_prefix }}"
      rhel: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
    exact_count: "{{ rhel_count }}"
    count_tag: rhel
  register: ec2_rhel

- name: Attach additional network interface to RHEL nodes
  ec2_eni:
    instance_id: "{{ item.id }}"
    device_index: 1
    subnet_id: "{{ ec2_private_subnet.subnet.id }}"
    private_ip_address: "10.0.3.{{ 10 + item.ami_launch_index|int }}"
    region: "{{ region }}"
    attached: yes
    state: present
  with_items: "{{ ec2_rhel.tagged_instances }}"
  register: eni

- debug:
    var: eni

- name: Set additional interfaces to auto delete on instance termination
  ec2_eni:
    eni_id: "{{ item.interface.id }}"
    delete_on_termination: yes
    region: "{{ region }}"
  with_items: "{{ eni.results }}"
  register: eni_results

- debug:
    var: eni_results

- name: Create RHEL Tower instances
  ec2:
    assign_public_ip: yes
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    instance_type: "{{ tower_instance_type }}"
    image: "{{ regions[region][rhel_ver].ami }}"
    vpc_subnet_id: "{{ ec2_subnet.subnet.id }}"
    wait: true
    instance_tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-tower_rhel"
      username: "{{ local_user }}"
      workshop_prefix: "{{ workshop_prefix }}"
      tower_rhel: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
    exact_count: "{{ tower_rhel_count }}"
    count_tag: tower_rhel
  register: ec2_tower_rhel
  when: tower_rhel_count is defined

- debug:
    var: ec2_rhel

- debug:
    var: ec2_tower_rhel

- name: Create Windows instances
  ec2:
    assign_public_ip: yes
    key_name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-key"
    group: "{{ workshop_abbrev }}-{{ workshop_prefix }}-win-sg"
    region: "{{ region }}"
    instance_type: "{{ win_instance_type }}"
    image: "{{ regions[region][win_ver].ami }}"
    vpc_subnet_id: "{{ ec2_subnet.subnet.id }}"
    user_data: "{{ lookup('file', '{{ winrm_path }}') }}"
    wait: true
    instance_tags:
      Name: "{{ workshop_abbrev }}-{{ workshop_prefix }}-win"
      username: "{{ local_user }}"
      workshop_prefix: "{{ workshop_prefix }}"
      win: "{{ workshop_abbrev }}-{{ workshop_prefix }}"
    exact_count: "{{ win_count }}"
    count_tag: win
  register: ec2_win

- debug:
    var: ec2_win

#===============================================================================
#  Verify hosts online
#===============================================================================

#---------------------------------------------------
#  RHEL
#---------------------------------------------------

- name: wait for SSH to answer on all hosts
  wait_for:
    port: 22
    host: "{{ item.public_ip }}"
    timeout: 300
  with_items: "{{ ec2_rhel.tagged_instances }}"

- name: add RHEL hosts to groups
  add_host:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix}}-rhel-{{ item.id }}"
    ansible_ssh_host: "{{ item.public_ip }}"
    groups: rhel_nodes
  with_items: "{{ ec2_rhel.tagged_instances }}"

- name: Create DNS records for RHEL
  route53:
    zone: "{{ domain_name }}"
    type: "CNAME"
    ttl: "300"
#    record: "{{ workshop_prefix }}.node.{{ item.ami_launch_index }}.{{ domain_name }}"
    record: "node-{{ item.ami_launch_index }}.{{ workshop_prefix }}.{{ domain_name }}"
    value: "{{ item.dns_name }}"
#    wait: yes
    state: present
  loop: "{{ ec2_rhel.instances }}"
#  ignore_errors: true

- name: Create DNS records for RHEL Towers
  route53:
    zone: "{{ domain_name }}"
    type: "CNAME"
    ttl: "300"
#    record: "{{ workshop_prefix }}.tower.{{ item.ami_launch_index }}.{{ domain_name }}"
    record: "tower-{{ item.ami_launch_index }}.{{ workshop_prefix }}.{{ domain_name }}"
    value: "{{ item.dns_name }}"
#    wait: yes
    state: present
  loop: "{{ ec2_tower_rhel.instances }}"
  when: tower_rhel_count is defined

#---------------------------------------------------
#  Windows
#---------------------------------------------------

- name: wait for WinRM to answer on all hosts
  wait_for:
    port: 5986
    host: "{{ item.public_ip }}"
    timeout: 300
  with_items: "{{ ec2_win.tagged_instances }}"

- name: add Windows hosts to groups
  add_host:
    name: "{{ workshop_abbrev }}-{{ workshop_prefix}}-win-{{ item.id }}"
    ansible_ssh_host: "{{ item.public_ip }}"
    groups: win_nodes
  with_items: "{{ ec2_win.tagged_instances }}"

- name: Create DNS records for Windows
  route53:
    zone: "{{ domain_name }}"
    type: "CNAME"
    ttl: "300"
#    record: "{{ workshop_prefix }}.win2016.{{ item.ami_launch_index }}.{{ domain_name }}"
    record: "win2016-{{ item.ami_launch_index }}.{{ workshop_prefix }}.{{ domain_name }}"
    value: "{{ item.dns_name }}"
#    wait: yes
    state: present
  loop: "{{ ec2_win.instances }}"
#  ignore_errors: true

...
