---
###################################
# Common Packages
###################################
- include_tasks: nodes_setup.yml

###################################
# Deploy walkthrough scripts
###################################
- include_tasks: walkthroughs.yml
  when: install_examples

###################################
# Base setup of Tower
###################################
# - import_tasks: tower_setup.yml

###################################
# tower-cli users setup
###################################
# - import_tasks: user_setup.yml
