---

- name: Download get-pip.py script
  command: /usr/bin/curl 'https://bootstrap.pypa.io/get-pip.py' -O chdir={{ remote_user_home }}
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true

- name: Python install pip
  command: /usr/bin/python {{ remote_user_home }}/get-pip.py chdir={{ remote_user_home }}
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true

- name: Pip install passlib
  pip: name=passlib state=present
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true
  
- name: Setup cockpit account
  shell: /usr/sbin/useradd --home /home/{{ admin_username }} {{ admin_username }} && echo {{ admin_username }}:{{ admin_password }} | chpasswd â€“crypt-method=SHA512
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true

- name: Create admin account
  htpasswd: name={{ admin_username }}  password={{ admin_password }}  path={{ htpasswd_path }}  state=present
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true

- name: Setup cluster role
  shell: /usr/bin/oc adm policy add-cluster-role-to-user cluster-admin {{ admin_username }}
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true

- name: Create test users
  shell: /usr/bin/htpasswd -b {{ htpasswd_path }} {{ student_name_prefix }}{{ item }} {{ student_pass_prefix }}{{ item }}
  with_sequence: count={{ student_count }}
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  become: true
