---

- name: Cache docker images
  hosts: nodes
  remote_user: ec2-user
  vars:
    state: 'present'
  tasks:
    - name: Docker pull images
      docker_image:
        name: "{{ item }}"
      become: true
      with_items:
       - registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7
       - registry.access.redhat.com/rhscl/postgresql-95-rhel7
       - registry.access.redhat.com/openshift3/jenkins-2-rhel7
       - docker.io/sonatype/nexus3:3.7.1
       - docker.io/openshiftdemos/gogs:0.11.34
       - docker.io/openshiftdemos/sonarqube:7.0
       - docker.io/eclipse/che-server:6.5.0
       - docker.io/openshift/deployment-example:v1
       - docker.io/openshift/deployment-example:v2
