# file: roles/container_check_stp/tasks/main.yml
---

- name: Copy container_check.stp
  become: yes
  copy:
    src: container_check.stp
    dest: /home/{{ system_user }}/workshopfiles/container_check.stp 
    group: "{{ system_user }}"
    owner: "{{ system_user }}"
    mode: 0755

# - name: Install libcap-ng-utils
#   become: yes
#   yum:
#     name: libcap-ng-utils
#     state: present
