---

#---------------------------------------------------
# Master
#---------------------------------------------------
- name: Generating master key for ec2-user
  user: "name={{ remote_user_name }} generate_ssh_key=yes"
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"

- name: Register master pub key
  shell: /usr/bin/cat ~/.ssh/id_rsa.pub
  delegate_to: "{{ master_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  register: "master_rsa_pub"

- name: Install master pub key on bastion
  authorized_key: user="{{ remote_user_name }}" key="{{  master_rsa_pub.stdout  }}"
  delegate_to: "{{ item }}"
  remote_user: "{{ remote_user_name }}"
  with_items:
   - "{{ bastion_public_ip }}"

- name: Install master pub key on nodes
  authorized_key: user="{{ remote_user_name }}" key="{{  master_rsa_pub.stdout  }}"
  delegate_to: "{{ item.public_ip }}"
  remote_user: "{{ remote_user_name }}"
  with_items:
   - "{{ nodes_ip }}"

#---------------------------------------------------
# Bastion
#---------------------------------------------------
- name: Generating bastion key for ec2-user
  user: "name={{ remote_user_name }} generate_ssh_key=yes"
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ remote_user_name }}"

- name: Register bastion pub key
  shell: /usr/bin/cat ~/.ssh/id_rsa.pub
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  register: "bastion_rsa_pub"

- name: Install bastion pub key on master
  authorized_key: user="{{ remote_user_name }}" key="{{  bastion_rsa_pub.stdout  }}"
  delegate_to: "{{ item }}"
  remote_user: "{{ remote_user_name }}"
  with_items:
   - "{{ master_public_ip }}"

- name: Install bastion pub key on nodes
  authorized_key: user="{{ remote_user_name }}" key="{{  bastion_rsa_pub.stdout  }}"
  delegate_to: "{{ item.public_ip }}"
  remote_user: "{{ remote_user_name }}"
  with_items:
   - "{{ nodes_ip }}"

- name: Run ssh-keyscan to add master to known_hosts
  shell: ssh-keyscan {{  master_private_dns_name  }} >> ~/.ssh/known_hosts
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ remote_user_name }}"

- name: Run ssh-keyscan to add nodes to known_hosts
  shell: ssh-keyscan {{  item.private_dns_name  }} >> ~/.ssh/known_hosts
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ remote_user_name }}"
  with_items:
   - "{{ nodes_ip }}"
