# file: group_vars
################################################################################
#
#                  ////IMPORTANT////
#
#      Prefixed to all resources for cleanup & identifcation.
################################################################################

# Ensure that the name does not include special characters such as underscores, etc.
workshop_prefix:                  "tower"
execution:                        "local" # when not running from Tower, define this variable

################################################################################
# ANSIBLE ROLE KEY         |      VALUE
################################################################################
# aws                      |      deployment working dir 
deploy_working_dir:               "{{ lookup('env','PWD') }}/.redhatgov"
# aws                      |      AWS API KEYS
aws_access_key:                   ""
aws_secret_key:                   ""
# aws                      |      AWS Route 53
domain_name:                      ""
zone_id:                          ""
# aws                      |      AWS Node Counts
tower_rhel_count:                 "2"            # RHEL Ansible Tower node(s)
rhel_count:                       "2"            # RHEL node(s)
win_count:                        "2"            # Windows node(s)
region:                           "us-east-2"    # AWS Region, configures ec2.ini too
ebs_root_block_size:              50
# aws.infra                |      AWS AMI IDs
#-------------------------------------------------------------------------------
# us-east-1
nodes.rhel.ami_id:                "ami-0456c465f72bd0c95" # RHEL-7.5_HVM-20180813-x86_64-0-Access2-GP2
nodes.win.ami_id:                 "ami-01945499792201081" # Windows_Server-2016-English-Full-Base-2018.09.15
# us-east-2
nodes.rhel.ami_id:                "ami-04268981d7c33264d" # RHEL-7.5_HVM-20180813-x86_64-0-Access2-GP2
nodes.win.ami_id:                 "ami-0ca3e3965ada31684" # Windows_Server-2016-English-Full-Base-2018.09.15
#-------------------------------------------------------------------------------
# subscription_manager     |      Red Hat Subscription via Cloud Access
cloud_access:                     true
# subscription_manager     |      Red Hat Subscription via username & password
username:                         ""
password:                         ""
pool_id:                          ""
# subscription_manager     |      Red Hat Subscription via activation keys
rhsm_activationkey:               ""
rhsm_org_id:                      ""
#-------------------------------------------------------------------------------
# LetsEncrypt              |      email
letsencrypt_email:                "someone@redhat.com"
letsencrypt:                      false
#-------------------------------------------------------------------------------
# wetty                    |      password
workshop_password:                "" # Note that Windows 2016 requires 3 character classes and 10 characters
rabbit_password:                  "" # Note that RabbitMQ password cannot have special characters
#-------------------------------------------------------------------------------

################################################################################
# ANSIBLE config           |      VALUE
################################################################################
# Dynamic Inventory 
inventory_working_dir:            "{{ lookup('env','PWD') }}/inventory"
# Ansible SSH Key Location |      SSH Key Vars
winrm_path:                       "{{ deploy_working_dir }}/{{ workshop_prefix }}-winrm"
ssh_key_path:                     "{{ deploy_working_dir }}/{{ workshop_prefix }}-key"
vpc_id_path:                      "{{ deploy_working_dir }}/{{ workshop_prefix }}-vpc_id"
vpc_route_path:                   "{{ deploy_working_dir }}/{{ workshop_prefix }}-vpc_route"
vpc_subnet_path:                  "{{ deploy_working_dir }}/{{ workshop_prefix }}-vpc_subnet"
vpc_rhel_ids_path:                "{{ deploy_working_dir }}/{{ workshop_prefix }}-vpc_rhel_ids"
ansible_ssh_private_key_file:     "{{ ssh_key_path }}"
system_user:                      "ec2-user"    # AWS
local_user:                       "{{ ansible_env.USERNAME }}"
