---
# tasks file for cockpit
- name: Install cockpit
  block:
  - name: Ensure cockpit packages exist
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - cockpit
    - cockpit-dashboard
    - cockpit-shell
    - cockpit-ws
  - name: Ensure cockpit is started
    service:
      name: cockpit.socket
      state: started
      enabled: yes

