# file: roles/cockpit/tasks/main.yml
---

# subscription-manager register --auto-attach --username=<rhnuser> --password=<rhnpasswd>
# subscription-manager repos --enable=rhel-7-server-extras-rpms
# subscription-manager repos --enable=rhel-7-server-optional-rpms

- name: Install Cockpit
  become: yes
  yum: name="{{item}}" state=present
  with_items: 
    - cockpit 
    - cockpit-docker
    - zsh
    - rsync
    - vim
    - wget

- name: Enable Cockpit
  become: yes
  systemd: 
    name: cockpit  
    state: started

#############################################################################################
# To make a SHA512 password run this on a RHEL instance.
# http://passlib.readthedocs.io/en/stable/lib/passlib.hash.sha256_crypt.html
# http://docs.ansible.com/ansible/latest/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
#
# python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.using(rounds=5000).hash('redhat123')"
#############################################################################################
- name: Create Cockpit user
  become: yes
  user:
    name: cockpit
    shell: "/bin/zsh"
    state: present
    groups: "{{ system_user }},adm"
    password: "$6$XhplkGk/5yR/qijY$vBq.u1/8BlGqbz00sA9INstZlvbhtr4uHqJMBKC31Bxxx/NdW8RX2135QGdNRK74/RqnkJqCx9IrxFnumSRjj0"
    createhome: true  
    update_password: always

- name: Add Cockpit User to /etc/sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    insertafter: "NOPASSWD: ALL"
    line: 'cockpit         ALL=(ALL)       NOPASSWD: ALL'  #/bin/docker'
    validate: 'visudo -cf %s'
    backup: yes

# - name: Copy over workshopfiles to cockpit home dir too
#   command: cp -R /home/ec2-user/workshopfiles/ /home/cockpit/

# - name: Change ownership of files
#   file:
#     path: "/home/cockpit/workshopfiles"
#     owner: cockpit
#     group: ec2-user
#     mode: 0755
#     recurse: true
#     state: directory 

# NOT enabled be default on RHEL 7.3 AMI
# - name: Firewalld setup
#   become: yes
#   firewalld: 
#     permanent: true
#     port: 9090/tcp
#     service: cockpit
#     state: enabled

