---

- debug:
    msg: "Unsubscribing IP {{ public_ip }}"

- name: Unsubscribe VM
  redhat_subscription:
    state: "absent"
  delegate_to: "{{ public_ip }}"
  remote_user: "{{ remote_user_name }}"
  ignore_errors: true
  become: true
